few_shots = [
    {"Question": "How much is the total price of the inventory for all LG brand?",
     "SQLQuery": "SELECT SUM(stock_quantity*price) FROM products WHERE brand = 'LG' AND category = 'Phone';",
     "SQLResult": "Result of the SQL query",
     "Answer": "31516"},

    {"Question": "What is the total revenue generated by selling Apple laptops?",
     "SQLQuery": """SELECT SUM((p.price - (p.price*d.pct_discount/100))*stock_quantity) AS total_revenue 
        FROM products AS p 
        INNER JOIN discounts AS d ON p.product_id = d.product_id 
        WHERE p.brand = 'Apple' AND p.category = 'Laptop';""",
     "SQLResult": "Result of the SQL query",
     "Answer": "201445"},

    {"Question": "If all Sony Tablets are sold today at their listed prices, what would be the total revenue?",
     "SQLQuery": "SELECT SUM(price * stock_quantity) FROM products WHERE brand = 'Sony' AND category = 'Tablet';",
     "SQLResult": "Result of the SQL query",
     "Answer": "658554"}
]
